"""AI-powered rule generator for 'warden rules generate'.

Detects project language/framework and asks the LLM to produce
type:ai rules in the .warden/rules/llm_generated.yml format.
"""

from pathlib import Path
from typing import Any

import structlog
import yaml

logger = structlog.get_logger(__name__)

REQUIRED_FIELDS: frozenset[str] = frozenset(
    {"id", "name", "category", "severity", "isBlocker", "description", "enabled", "type"}
)
OUTPUT_FILENAME = "llm_generated.yml"

_RULE_GEN_PROMPT = """\
You are a senior security engineer writing Warden rule definitions.

Project details:
- Language: {language}
- Framework: {framework}

Generate 3-5 rules for this project in YAML format.
Each rule MUST have exactly these fields:
  id: (kebab-case string, unique)
  name: (human-readable string)
  category: (one of: security, convention, performance, custom, architectural, consistency, backend-ipc, logic)
  severity: (one of: critical, high, medium, low)
  isBlocker: (true or false)
  description: (specific, actionable directive — not vague. Tells the LLM auditor exactly what to flag.)
  enabled: true
  type: "ai"

Return ONLY a valid YAML block starting with `rules:` — no markdown, no explanation, no code fences.

Example output:
rules:
  - id: no-raw-sql-concat
    name: No Raw SQL Concatenation
    category: security
    severity: critical
    isBlocker: true
    description: Detect SQL queries built via string concatenation or f-strings containing SELECT/INSERT/UPDATE/DELETE. Flag any occurrence regardless of context.
    enabled: true
    type: ai
"""

_PY_FRAMEWORKS: frozenset[str] = frozenset(
    {"django", "flask", "fastapi", "pyramid", "tornado", "fastmcp", "mcp"}
)
_JS_FRAMEWORKS: frozenset[str] = frozenset(
    {"react", "vue", "angular", "next", "nuxt", "svelte", "express", "nest"}
)


def _infer_language(framework: str) -> str:
    fw = framework.lower()
    if fw in _PY_FRAMEWORKS:
        return "python"
    if fw in _JS_FRAMEWORKS:
        return "javascript/typescript"
    return "unknown"


async def generate_rules_for_project(
    project_path: Path,
    llm_service: Any,
    force: bool = False,
) -> int:
    """Generate AI rules for a project and write to .warden/rules/llm_generated.yml.

    Args:
        project_path: Root directory of the project.
        llm_service: LLM service instance with a ``complete_async`` method.
        force: Overwrite existing file when True; skip when False.

    Returns:
        Number of rules written, or -1 when skipped (file exists, force=False).

    Raises:
        ValueError: LLM output is unparseable or missing required fields.
    """
    from warden.analysis.application.discovery.framework_detector import detect_frameworks_async  # noqa: PLC0415

    output_path = project_path / ".warden" / "rules" / OUTPUT_FILENAME

    if output_path.exists() and not force:
        logger.info("llm_generated_rules_exist_skip", path=str(output_path))
        return -1

    # Detect language + framework
    detection = await detect_frameworks_async(project_path)
    framework = detection.primary_framework.value if detection.primary_framework else "unknown"
    language = _infer_language(framework)

    logger.info("rule_generation_started", language=language, framework=framework)

    prompt = _RULE_GEN_PROMPT.format(language=language, framework=framework)

    response = await llm_service.complete_async(
        prompt=prompt,
        system_prompt="You are a Warden rule definition generator. Output YAML only.",
    )
    raw: str = response.content if hasattr(response, "content") else str(response)

    # Parse
    try:
        data = yaml.safe_load(raw)
    except yaml.YAMLError as exc:
        raise ValueError(f"LLM returned invalid YAML: {exc}") from exc

    if not isinstance(data, dict) or "rules" not in data:
        raise ValueError(f"LLM output missing 'rules' key. Got: {raw[:300]}")

    rules = data["rules"]
    if not isinstance(rules, list) or len(rules) == 0:
        raise ValueError("LLM returned empty rules list.")

    # Validate required fields per rule
    for i, rule in enumerate(rules):
        if not isinstance(rule, dict):
            raise ValueError(f"Rule #{i} is not a mapping.")
        missing = REQUIRED_FIELDS - set(rule.keys())
        if missing:
            raise ValueError(f"Rule #{i} (id={rule.get('id', '?')!r}) missing fields: {missing}")
        if rule.get("type") != "ai":
            raise ValueError(
                f"Rule #{i} (id={rule.get('id', '?')!r}) must have type: ai, got: {rule.get('type')!r}"
            )

    # Write
    output_path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Auto-generated by 'warden rules generate'\n"
        "# Review this file before committing to your repository.\n"
        "# To regenerate: warden rules generate --force\n\n"
    )
    output_path.write_text(
        header + yaml.dump(data, default_flow_style=False, allow_unicode=True),
        encoding="utf-8",
    )

    logger.info("llm_generated_rules_written", path=str(output_path), count=len(rules))
    return len(rules)
